### ISSUE TITLE
Custodian simply can't spike Potmobiles and Haulers

### ISSUE THREAD

**Issue by Phreelosu** [NotSomeoneElse/Cloudburst#4]
https://thunderstore.io/package/Moffein/Potmobile/ 

Enemy potmobiles cannot be spiked and are just throwing errors on ".Start" and ".FixedUpdate"

Line 14527 in the log where it first appears as an error, can very easily replicate though

[LogOutput.log](https://github.com/NotSomeoneElse/Cloudburst/files/13257660/LogOutput.log)

^ same log as #3 's attached log

PS: Unsure if its related but while they arent throwing any errors or whatsoever, you also just cant spike Sigma Constructs (from SpikeStrip / https://thunderstore.io/package/SpikestripModding/Spikestrip2_0/) and Frost Wisps (from ForgottenRelics / https://thunderstore.io/package/PlasmaCore3/Forgotten_Relics/)

**Comment by TheTimeSweeper** [comment]
funny code for potmobiles and haulers implemented.

issue for frost wisps and sigma constructs lies on them. their hurtbox volume is an astronomical amount because they have the bad 100 scale armature. they will have to re-export from blender

![image](https://github.com/user-attachments/assets/64518106-c04a-4f2d-954e-64f902401c6d)  
*wew lad*

added a hacky fix for them anyways
